GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/home/icb/alessandro.palma/miniconda3/envs/IMPA/lib/python3.9/site-packages/pytorch_lightning/trainer/configuration_validator.py:72: You passed in a `val_dataloader` but have no `validation_step`. Skipping val loop.
wandb: Currently logged in as: allepalma. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.15.12
wandb: Run data is saved locally in ../project_folder/experiments/20231107_bbbc021_try/wandb/run-20231107_095707-m71svux1
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run major-eon-35
wandb: ‚≠êÔ∏è View project at https://wandb.ai/allepalma/bbbc021_try
wandb: üöÄ View run at https://wandb.ai/allepalma/bbbc021_try/runs/m71svux1

  | Name             | Type         | Params
--------------------------------------------------
0 | embedding_matrix | Embedding    | 960   
1 | generator        | DataParallel | 24.3 M
2 | style_encoder    | DataParallel | 14.3 M
3 | discriminator    | DataParallel | 14.3 M
4 | mapping_network  | DataParallel | 11.3 K
--------------------------------------------------
53.0 M    Trainable params
960       Non-trainable params
53.0 M    Total params
211.840   Total estimated model params size (MB)
SLURM auto-requeueing enabled. Setting signal handlers.
Thread SenderThread:
Traceback (most recent call last):
  File "/home/icb/alessandro.palma/miniconda3/envs/IMPA/lib/python3.9/site-packages/wandb/sdk/internal/internal_util.py", line 49, in run
    self._run()
  File "/home/icb/alessandro.palma/miniconda3/envs/IMPA/lib/python3.9/site-packages/wandb/sdk/internal/internal_util.py", line 100, in _run
    self._process(record)
  File "/home/icb/alessandro.palma/miniconda3/envs/IMPA/lib/python3.9/site-packages/wandb/sdk/internal/internal.py", line 328, in _process
    self._sm.send(record)
  File "/home/icb/alessandro.palma/miniconda3/envs/IMPA/lib/python3.9/site-packages/wandb/sdk/internal/sender.py", line 387, in send
    send_handler(record)
  File "/home/icb/alessandro.palma/miniconda3/envs/IMPA/lib/python3.9/site-packages/wandb/sdk/internal/sender.py", line 409, in send_request
    send_handler(record)
  File "/home/icb/alessandro.palma/miniconda3/envs/IMPA/lib/python3.9/site-packages/wandb/sdk/internal/sender.py", line 1146, in send_request_summary_record
    self._update_summary_record(record.request.summary_record.summary)
  File "/home/icb/alessandro.palma/miniconda3/envs/IMPA/lib/python3.9/site-packages/wandb/sdk/internal/sender.py", line 1140, in _update_summary_record
    self._update_summary()
  File "/home/icb/alessandro.palma/miniconda3/envs/IMPA/lib/python3.9/site-packages/wandb/sdk/internal/sender.py", line 1160, in _update_summary
    with open(summary_path, "w") as f:
BrokenPipeError: [Errno 108] Cannot send after transport endpoint shutdown: '../project_folder/experiments/20231107_bbbc021_try/wandb/run-20231107_095707-m71svux1/files/wandb-summary.json'
wandb: ERROR Internal wandb error: file data was not synced
wandb: While tearing down the service manager. The following error has occurred: [Errno 32] Broken pipe
